@HOSTNAME = http://localhost
@PORT = 3000
@HOST = {{HOSTNAME}}:{{PORT}}
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTA3YzgyYzBkNTY5NDE4ZTc5ZmY1NGUiLCJlbWFpbCI6ImFkbUBsaXZlLmNvbSIsInJvbGUiOiJhZG1pbmlzdHJhZG9yIiwiaWF0IjoxNjk1MDQ5NjMxLCJleHAiOjE2OTUxMzYwMzF9.vvYMtnxgPJsGrIqMl8bNVzyOHvqRy8TkTjs5xx_2Q2s


@BOOK_ID=6508421dd5a5e4a632402bc7

### 
# @name HealthCheck
GET {{HOST}}/health-check

###
# @name PostBook
POST {{HOST}}/books
content-type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "Arquitetura Limpa",
  "author": "Bob Uncle",
  "available": true
}

###
# @name GestListBOoks
GET {{HOST}}/books
Authorization: Bearer {{TOKEN}}

###
# @name GestListBooksAvailable
GET {{HOST}}/books/available
Authorization: Bearer {{TOKEN}}

###
# @name GetBOokById
GET {{HOST}}/books/{{BOOK_ID}}
Authorization: Bearer {{TOKEN}}

###
# @name UpdateBookById
PUT {{HOST}}/books/{{BOOK_ID}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "Biblía Sagrada",
  "author": "Apostolos"
}

###
# @name UpdateAvailableBook
PUT {{HOST}}/books/available/{{BOOK_ID}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "available": true
}

###
# @name DeleteBookById
DELETE {{HOST}}/books/{{BOOK_ID}}
Authorization: Bearer {{TOKEN}}

### 
# @name PostNewUser
POST {{HOST}}/user
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "name": "Joelton Lino Luz",
  "email": "adm@live.com",
  "password": "s3nh@ForTe",
  "type": "administrador"
}

###
# @name login
POST {{HOST}}/login
Content-Type: application/json

{
  "email": "adm@live.com",
  "password": "s3nh@ForTe"
}
