@HOSTNAME = http://localhost
@PORT = 3000
@HOST = {{HOSTNAME}}:{{PORT}}
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTA5MGUxMDQ3NTI4MDc1MjIyMWQ4N2YiLCJlbWFpbCI6ImNsaWVudGVAbGl2ZS5jb20iLCJyb2xlIjoiY2xpZW50ZSIsImlhdCI6MTY5NTA5MjQzNSwiZXhwIjoxNjk1MTc4ODM1fQ.Y-gnWxD40YY72ZHytDBUUfY15PWsmm4CI6F5jR8ClVg


@BOOK_ID=65090e56475280752221d884

### 
# @name HealthCheck
GET {{HOST}}/health-check

###
# @name PostBook
POST {{HOST}}/books
content-type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "Arquitetura Suja",
  "author": "Bobo Corte",
  "available": true
}

###
# @name GestListBOoks
GET {{HOST}}/books
Authorization: Bearer {{TOKEN}}

###
# @name GestListBooksAvailable
GET {{HOST}}/books/available
Authorization: Bearer {{TOKEN}}

###
# @name GetBookById
GET {{HOST}}/books/{{BOOK_ID}}
Authorization: Bearer {{TOKEN}}

###
# @name UpdateBookById
PUT {{HOST}}/books/{{BOOK_ID}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "Arquitetura Suja!",
  "author": "Bob Thinx"
}

###
# @name UpdateAvailableBook
PUT {{HOST}}/books/available/{{BOOK_ID}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "available": false
}

###
# @name DeleteBookById
DELETE {{HOST}}/books/{{BOOK_ID}}
Authorization: Bearer {{TOKEN}}

### 
# @name PostNewUser
POST {{HOST}}/user
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "name": "Joelton Lino Luz",
  "email": "cliente@live.com",
  "password": "s3nh@ForTe",
  "type": "cliente"
}

###
# @name login
POST {{HOST}}/login
Content-Type: application/json

{
  "email": "cliente@live.com",
  "password": "s3nh@ForTe"
}
